name: Build and Deploy to ECR and Helm

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}   # set at job level

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # required input

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to ECR
        run: |
          docker build -t "$ECR_REPOSITORY:$IMAGE_TAG" .
          docker push "$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          echo "${{ secrets.HELM_KUBECONFIG }}" > "$HOME/.kube/config"

      - name: Upgrade Helm release
        run: |
          helm upgrade retail-application ./charts \
            --install \
            --set image.repository="$ECR_REPOSITORY" \
            --set image.tag="$IMAGE_TAG"
